---
title: "Midterm practice review and study guide"
output: html_notebook
---

```{r}
library(dcData)
library(mosaicData)
library(mosaic)
library(tidyverse)
library(tidyr)
```

Add a new chunk by clicking the *Insert Chunk* button on the toolbar or by pressing *Cmd+Option+I*.

some simple functions to know:
```{r}
BabyNames %>% nrow() #total cases in table
BabyNames %>% names() #names of variables
BabyNames %>% head(3) #first 3 cases
BabyNames %>% str() #view of first few cases
BabyNames%>% glimpse() # view of first few cases
```

modifying data table and storing it as its original name
```{r}
BabyNames <-
  BabyNames %>% 
  filter(year == 1998)
```

named arguments
```{r}
BabyNames %>%
  group_by(sex)%>% 
  summarise(total = sum(count)) # summarise in named argument form
```

data wrangling computation
```{r}
Princes <- 
  BabyNames %>%
  filter(name == "Prince") %>%
  group_by(year, sex) %>%
  summarise(yearlyTotal = sum(count))

#using chaining syntax
Princes %>%
  ggplot(aes(x = year, y = yearlyTotal)) +
  geom_point(aes(color = sex)) +
  geom_vline(xintercept = 1978) +
  ylim(0,640) + xlim(1880, 2015)

# versus not chaining syntax
Princes <-
  summarise(
    group_by(
      filter(BabyNames, name == "Prince"),
      year, sex),
    yearlyTotal = sum(count))
               
```



```{r}
ggplot(data = NCHS, aes(x = bmi)) + geom_density(adjust = 1, alpha = 0.4, color=NA) + aes(color = sex, fill = sex) + facet_wrap(~pregnant, ncol = 4) + labs(title = "") + theme(legend.position ='right') + theme_bw()

```





