---
title: "Capstone Group Evaluations"
author: "Diane Kim"
date: ""
output: html_notebook
---


## Who are you evaluating?

Damin Park


# Evaluation Areas

### 1. Intellectual Contributions.

*Understanding the project, doing the research, evaluating and interpreting data, creative efforts and problem solving insight, providing intellectual leadership for group.* 

Score (out of 10): 10

Justification/Examples:

Damin showed strong leadership skills in guiding our project. We both came up 
with ideas, but Damin had a lot do creative ideas for what kind of graphs 
we should make.


### 2. Team Support.

*Enthusiasm, commitment to project, cooperation, respect for other persons’ ideas, willingness to compromise as appropriate, receptiveness to constructive feedback.* 

Score (out of 10): 10

Justification/Examples:
Damin was respectful in discussing our ideas and made sure to take what I said
into consideration when we both made decisions on what to add.



### 3. Communication Contributions. 

*Effectiveness of communication within team, quality of written work, contributions toward creation of presentation and other written work.* 

Score (out of 10): 10

Justification/Examples:

Worked well in communicating expectations from the project and had equal 
contributions as team member.


### 4. Time Contributions.

*Keeping team on task, meeting deadlines, following through on plans, attendance at team meetings, does equal share of work.* 

Score (out of 10): 10

Justification/Examples:

Followed through on attendance of meetings and met deadlines together.



### 5. Overall / Other Contributions

*Score any additional contributions, general remarks, or overall impression of this person as a member of the group.*


Score (out of 10): 10

Justification/Examples:


Overall, it was a good experience working with Damin.


# Total Score (out of 50):  50





